platform :ios, '9.0'

target 'ZipAuthoring' do
  use_frameworks!
  
  
  pod 'AWSMobileClient'
  pod 'AWSDynamoDB'
  pod 'AWSUserPoolsSignIn'
  pod 'SwiftyJSON'
  pod 'SwiftHash'
  pod 'JGProgressHUD'
  pod 'AudioKit'
  
end
